import {
  Bell,
  BookDashed,
  Boxes,
  DollarSign,
  FileChartColumn,
  Megaphone,
  Settings,
  UsersRound,
} from "lucide-react";

export const navBarData = [
  {
    id: 1,
    label: "Dashboard",
    href: "/dashboard",
    icon: <BookDashed size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 2,
    label: "Utilisateurs",
    href: "/utilisateur",
    icon: <UsersRound size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 9,
    label: "Produits",
    href: "/produits",
    icon: <Boxes size={14} />,
  },
  {
    id: 3,
    label: "Annonces",
    href: "/annonces",
    icon: <Megaphone size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 4,
    label: "Transactions",
    href: "/transactions",
    icon: <DollarSign size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 5,
    label: "Notifications",
    href: "/notifications",
    icon: <Bell size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 6,
    label: "Rapports",
    href: "/rapports",
    icon: <FileChartColumn size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
  {
    id: 7,
    label: "Paramètres",
    href: "/parametres",
    icon: <Settings size={14} />,
    activeBg: "#647673",
    color: "#FFFFFF",
  },
];
